development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: root  
  database: btw_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: btw_test

production: &production
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: btw_production